### ISSUE TITLE
Generating new order files

### ISSUE THREAD

**Issue by MalloryJfeldman** [uwmadison-chm/mid-psychopy#1]
Hi All! This is an AWESOME task and i'm so grateful you made it open-source. We're hoping to run the task here at UNC but need to make it shorter to fit within our scan time. We're trying to generate new order files and are running into a wall. I can't see if/where the simulator spits out trials (and or where the num_trials variable is even coming into play). I'm a bit of a python novice so would appreciate any/all help!

**Comment by dgfitch** [comment]
Hi Mallory! I actually forgot about this task, so my brain contains almost no information about it. :laughing: 

This implementation sort of "cheats" on stimulus orders, which are quite complex for the MID and I don't remember all the rules. So what it does is preload some prefab orders from the files in the `orders/` directory.

You can see that happening here: https://github.com/uwmadison-chm/mid-psychopy/blob/f106460f83e8ccf4e71ea361b5b3f75b27b4c58e/mid.py#L441

The orders were generated by Jeanette Mumford, who's now at Stanford, so I can't clue you in on how to regenerate them to be shorter.

I think you could change those CSV files and change `num_trials` and it would work, but I don't know about how to make those changes scientifically valid, for that part you are on your own.

Good luck!
